In [3]:
'''
check the 3DPW dataset 
'''
import os
import cv2
import numpy as np
import pickle
import argparse
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D


dataset_path = r'S:\ACLab\datasets\3DPW'    # local 
dataset_path = os.path.join(dataset_path, 'sequenceFiles', 'test')
files = [os.path.join(dataset_path, f)
         for f in os.listdir(dataset_path) if f.endswith('.pkl')]
filename = files[0]
with open(filename, 'rb') as f:
    data = pickle.load(f, encoding='latin1')
    smpl_pose = data['poses']  # N x 72
    smpl_betas = data['betas']
    poses2d = data['poses2d']
    global_poses = data['cam_poses']
    genders = data['genders']
    valid = np.array(data['campose_valid']).astype(
        np.bool)  # indicate which cam pose aligned to image , maybe 0 failed
    num_people = len(smpl_pose)
    num_frames = len(smpl_pose[0])
    seq_name = str(data['sequence'])
    img_names = np.array(['imageFiles/' + seq_name + '/image_%s.jpg' % str(i).zfill(5) for i in range(num_frames)])
    cam_intrinsics = data['cam_intrinsics']
    jointPositions = data['jointPositions']  # 24 x 3  xyz

In [10]:
idx_frm = 0 
print('cam intrinsics')
print(cam_intrinsics) # intrinsics
print('subj0 and subj2') 
jt0 = jointPositions[0][idx_frm].reshape([-1,3]) 
jt1 = jointPositions[1][idx_frm].reshape([-1,3])
print(jt0)
print(jt1)

print('num frames', num_frames)
print('num of j3d', len(jointPositions[0]))

cam intrinsics
[[1.96923077e+03 0.00000000e+00 9.60000000e+02]
 [0.00000000e+00 1.96185286e+03 5.40000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
subj0 and subj2
[[ 0.54854517  0.65308058  0.29526967]
 [ 0.6067764   0.56833399  0.27412834]
 [ 0.48159859  0.56350798  0.28449615]
 [ 0.55498663  0.77958438  0.25543452]
 [ 0.61404759  0.16420403  0.26439937]
 [ 0.44535142  0.16155147  0.29119098]
 [ 0.55728512  0.91475461  0.27563103]
 [ 0.58034389 -0.28074045  0.19585223]
 [ 0.4740886  -0.2790132   0.23387573]
 [ 0.55221668  0.9688483   0.27721202]
 [ 0.59704333 -0.35163906  0.32158254]
 [ 0.47769424 -0.35091736  0.36820347]
 [ 0.5279714   1.18027207  0.23815653]
 [ 0.62265203  1.0875331   0.25342614]
 [ 0.45888629  1.07900055  0.25556381]
 [ 0.55096959  1.27026217  0.27748203]
 [ 0.75334397  1.10617265  0.29522139]
 [ 0.34951907  1.10034164  0.3208684 ]
 [ 0.75715719  0.83855337  0.27639662]
 [ 0.32051563  0.8264512   0.33110742]
 [ 0.7838267   0.56306853  0.28701458]
 [ 0.

In [11]:
idx_frm = 400
print('after 400 frames')
jt0 = jointPositions[0][idx_frm].reshape([-1,3]) 
jt1 = jointPositions[1][idx_frm].reshape([-1,3])
print(jt0)
print(jt1)  # not too far away.. 

after 400 frames
[[-0.4924076   0.18487712 -0.12158793]
 [-0.47835399  0.09712788 -0.17746622]
 [-0.54164353  0.09874743 -0.06887489]
 [-0.5184353   0.31059591 -0.15548317]
 [-0.47761398 -0.3060678  -0.20748696]
 [-0.57275992 -0.30084314 -0.02105384]
 [-0.49792265  0.44569607 -0.15885254]
 [-0.56340721 -0.74658142 -0.2564513 ]
 [-0.59880023 -0.7428527  -0.06750319]
 [-0.49634179  0.50001628 -0.15778897]
 [-0.44583107 -0.82442172 -0.22137519]
 [-0.497928   -0.81366489  0.02214934]
 [-0.52709428  0.71390038 -0.16879129]
 [-0.47237457  0.61307184 -0.23689017]
 [-0.55459998  0.61828314 -0.09508603]
 [-0.48336761  0.80393396 -0.15631884]
 [-0.45399644  0.65183957 -0.3685487 ]
 [-0.61513851  0.6504848   0.01436469]
 [-0.50882711  0.43080764 -0.51042004]
 [-0.71229068  0.39659667  0.05979905]
 [-0.43905108  0.25303662 -0.71103078]
 [-0.68841227  0.15010352  0.19110769]
 [-0.41313305  0.20540926 -0.78328862]
 [-0.67967388  0.07421128  0.24193145]]
[[ 0.59575571  0.12123519  0.1860229 ]
 [ 0.61

In [5]:
print(jt0.shape)

(24, 3)


In [9]:
%matplotlib qt

fig = plt.figure()
ax = Axes3D(fig)
ax.cla()
ax.scatter(jt0[:,0], jt0[:,1], jt0[:,2], c='r')
ax.scatter(jt1[:,0], jt0[:,1], jt0[:,2], c='b')
plt.xlabel('x')
plt.ylabel('y')
plt.show()